env:
  es6: true
  node: true
  jest: true

settings:
  alias:
    extensions: ['.ts']
    map:
      - ['~', './src']
  import/resolver:
    node:
      extensions: ['.js', '.ts']

parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: ./tsconfig.json

extends:
  - htmlacademy/node
  - airbnb-typescript/base
  - prettier

ignorePatterns:
  '**/express/public/**/*.js'

rules:
  '@typescript-eslint/quotes':
    - error
    - backtick
  '@typescript-eslint/comma-dangle':
    - error
    - always-multiline
  '@typescript-eslint/no-unused-vars':
    - error
    - vars: all
      args: after-used
      argsIgnorePattern: ^_
      caughtErrors: all
  '@typescript-eslint/explicit-function-return-type':
    - error
  '@typescript-eslint/await-thenable':
    - error
  '@typescript-eslint/no-misused-promises':
    - error
  '@typescript-eslint/require-await':
    - error
  '@typescript-eslint/no-non-null-assertion':
    - error
  '@typescript-eslint/restrict-template-expressions':
    - error
    - allowNumber: true
      allowBoolean: false
      allowAny: false
      allowNullable: false
  '@typescript-eslint/no-unnecessary-condition':
    - error
  object-curly-spacing:
    - error
    - always
  implicit-arrow-linebreak:
    - error
    - beside
  function-paren-newline:
    - error
    - consistent
  no-confusing-arrow:
    - error
    - allowParens: true
  no-process-exit:
    - error
  require-atomic-updates:
    - error
  no-console:
    - error
    - allow:
      - warn
      - error
      - info
  arrow-parens:
    - error
    - always
  no-param-reassign: off
  import/prefer-default-export: off
  import/extensions: off
