env:
  es6: true
  node: true

parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: ./tsconfig.json

extends:
  - htmlacademy/node
  - airbnb-typescript/base
  - prettier

rules:
  '@typescript-eslint/quotes':
    - error
    - backtick
  no-console: off
