env:
  es6: true
  node: true

settings:
  alias:
    extensions: ['.ts']
    map:
      - ['~', './src']
  import/resolver:
    node:
      extensions: ['.js', '.ts']

parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: ./tsconfig.json

extends:
  - htmlacademy/node
  - airbnb-typescript/base
  - prettier

rules:
  '@typescript-eslint/quotes':
    - error
    - backtick
  '@typescript-eslint/comma-dangle':
    - error
    - only-multiline
    - arrays: never
      objects: always
      imports: never
      exports: never
      functions: never
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: ^_
  import/prefer-default-export: off
  import/extensions: off
  no-console: off
