DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS offer_types;
DROP TABLE IF EXISTS offers;
DROP TABLE IF EXISTS categories;

CREATE TABLE users
(
  id SERIAL PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(50) NOT NULL,
  picture VARCHAR(50) NOT NULL
);

CREATE TABLE offer_types
(
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE offers
(
  id SERIAL PRIMARY KEY,
  picture VARCHAR(100) NOT NULL,
  title VARCHAR(50) NOT NULL,
  description VARCHAR(1000) NOT NULL,
  sum MONEY NOT NULL,
  created_date DATE NOT NULL,
  type_id INTEGER NOT NULL,
  FOREIGN KEY (type_id) REFERENCES offer_types (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);


CREATE TABLE categories
(
  id SERIAL PRIMARY KEY,
  name VARCHAR(50)
);
