DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS offers;

CREATE TABLE categories
(
  id SERIAL PRIMARY KEY,
  name VARCHAR(50)
);

CREATE TABLE offers
(
  id SERIAL PRIMARY KEY,
  picture VARCHAR(100) NOT NULL,
  title VARCHAR(50) NOT NULL,
  description VARCHAR(1000) NOT NULL,
  sum MONEY NOT NULL,
  created_date DATE NOT NULL
);
